sudo: required

language: c

os:
- linux
- linux-ppc64le
- linux-arm64
# - osx   # TODO: still problems with AVX2 support

compiler:
  - gcc
  - clang

# whether to test threads using callback backend
env:
  matrix:
    - BLOSC_TEST_CALLBACK=yes
    - BLOSC_TEST_CALLBACK=no

before_install: ./scripts/travis-before-install.sh

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - cmake --build . --config Release
  - ctest
