// Copyright (c) Meta Platforms, Inc. and affiliates.
// THIS FILE WAS AUTOMATICALLY GENERATED BY train_model.py

// clang-format off

#ifndef ZSTRONG_COMPRESS_SELECTORS_ML_SELECTOR_NUMERIC_MODEL
#define ZSTRONG_COMPRESS_SELECTORS_ML_SELECTOR_NUMERIC_MODEL

#include "openzl/compress/selectors/ml/gbt.h"

#ifdef __cplusplus
extern "C" {
#endif

// GENERATED GENERIC_NUMERIC MODEL GETTER FUNCTION
extern GBTModel  getGenericNumericGbtModel(FeatureGenerator featureGenerator);

#ifdef __cplusplus
}
#endif

#endif
