// Copyright (c) Meta Platforms, Inc. and affiliates.

#ifndef OPENZL_CODECS_SDDL2_H
#define OPENZL_CODECS_SDDL2_H

#include <stddef.h>
#include "openzl/zl_opaque_types.h"

#if defined(__cplusplus)
extern "C" {
#endif

/**
 * Graph ID for the SDDL2 (Simple Data Description Language v2) component.
 *
 * This is an enhanced bytecode execution engine for parsing and decomposing
 * structured data. It provides significant performance improvements over SDDL
 * v1 while maintaining compatibility with the OpenZL compression framework.
 *
 * The SDDL2 graph requires:
 * 1. Bytecode parameter (SDDL2_BYTECODE_PARAM)
 * 2. A successor graph to process the parsed segments
 *
 * Use the C++ wrapper openzl::graphs::SDDL2 for convenient graph construction.
 */
#define ZL_GRAPH_SDDL2                                         \
    (ZL_GraphID)                                               \
    {                                                          \
        ZL_StandardGraphID_simple_data_description_language_v2 \
    }

/**
 * Parameter ID at which the SDDL2 graph expects to receive the bytecode it
 * will execute.
 *
 * The bytecode should be generated by the SDDL compiler or assembler and
 * passed as a local copy parameter.
 */
#define SDDL2_BYTECODE_PARAM 7685

/**
 * Registers a Simple Data Description Language v2 graph with the provided
 * (pre-compiled) @p bytecode and @p destination graph.
 *
 * This is the enhanced SDDL2 VM providing significant performance improvements
 * over SDDL v1 while maintaining compatibility with the OpenZL framework.
 *
 * @param compressor The compressor instance to register the graph with
 * @param bytecode Pointer to the compiled SDDL2 bytecode
 * @param bytecode_size Size of the bytecode in bytes
 * @param destination The graph to process the parsed segments
 * @return The registered graph ID
 *
 * @note The bytecode should be generated by the SDDL compiler or assembler.
 *       The bytecode format is documented in the SDDL2 specification.
 */
ZL_GraphID ZL_Compressor_registerSDDL2Graph(
        ZL_Compressor* compressor,
        const void* bytecode,
        size_t bytecode_size,
        ZL_GraphID destination);

#if defined(__cplusplus)
}
#endif

#endif // OPENZL_CODECS_SDDL2_H
